build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:bookworm"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:bookworm"
  armv7: "ghcr.io/home-assistant/armv7-base-debian:bookworm"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: eBUSd"
  org.opencontainers.image.description: "This Add-on runs eBUSd, a daemon for handling communication with eBUS devices"
  org.opencontainers.image.source: "https://github.com/Hoellenwesen/ha-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
