build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.10-alpine.3.16"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.10-alpine.3.16"
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.10-alpine.3.16"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.10-alpine.3.16"
  i386: "ghcr.io/home-assistant/i386-base-python:3.10-alpine.3.16"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: DahuaVTO2MQTT"
  org.opencontainers.image.description: "Listens to events from Dahua VTO unit and publishes them via MQTT Message."
  org.opencontainers.image.source: "https://github.com/Hoellenwesen/ha-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
