build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
  armv7: "ghcr.io/home-assistant/armv7-base:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: DahuaVTO2MQTT"
  org.opencontainers.image.description: "Listens to events from Dahua VTO unit and publishes them via MQTT Message."
  org.opencontainers.image.source: "https://github.com/Hoellenwesen/ha-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
