build_from:
  aarch64: "ghcr.io/hassio-addons/base-python/aarch64:stable"
  amd64: "ghcr.io/hassio-addons/base-python/amd64:stable"
  armhf: "ghcr.io/hassio-addons/base-python/armhf:stable"
  armv7: "ghcr.io/hassio-addons/base-python/armv7:stable"
  i386: "ghcr.io/hassio-addons/base-python/i386:stable"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: DahuaVTO2MQTT"
  org.opencontainers.image.description: "Listens to events from Dahua VTO unit and publishes them via MQTT Message."
  org.opencontainers.image.source: "https://github.com/Hoellenwesen/ha-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
