name: DahuaVTO2MQTT
version: "1.0.5"
slug: dahua_mqtt
description: Listens to events from Dahua VTO unit and publishes them via MQTT Message
url: "https://github.com/Hoellenwesen/ha-addons/tree/main/DahuaVTO2MQTT"
startup: services
arch:
  - armv7
  - aarch64
  - amd64
image: "ghcr.io/hoellenwesen/ha-addon-dahuavto2mqtt-{arch}"
init: false
options:
  vto:
    host: '192.168.1.110'
    ssl: false
    username: 'admin'
    password: 'admin'
  mqtt:
    host: core-mosquitto
    port: 1883
    username: 'homeassistant'
    password: 'homeassistant'
    prefix: DahuaVTO
  debug: false
schema:
  vto:
    host: str
    ssl: bool
    username: str
    password: str
  mqtt:
    host: str
    port: int
    username: str
    password: str
    prefix: str
  debug: bool
